var ANAP_CONFIG = {
    BASE_DIRECTORY: '/',
    REFRESH_TIMER_SMALL: 10000,
    REFRESH_TIMER_MEDIUM: 15000,
    REFRESH_TIMER_BIG: 30000,
    MEDIUM_WORLD_THRESHOLD: 100,
    BIG_WORLD_THRESHOLD: 300,
    APP_VERSION: '0.7.6',
    SETTINGS_VERSION: '2',
    OFFLINE: false,
};

export default ANAP_CONFIG;
